spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rentDB?createDatabaseIfNotExist=true&autoReconnect=true&useSSL=false
    username: viksingh
    password: Vikas9899@a
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MYSQL5Dialect