spring:
    datasource:
        url: jdbc:mysql://localhost:3306/rentDB?createDatabaseIfNotExist=true
        username: viksingh
        password: Vikas9899@a
    jpa:
      hibernate:
        naming:
         physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
